baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Pyfyle Logs'
[languages]
[languages.en.params]
languageName = "English"
title = "Pyfyle Logs"
subtitle = ""
owner = ""
keywords = ""
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"
[languages.en.params.logo]
logoText = "Pyfyle Logs"
logoHomeLink = "/"
